name: Playground

on:
  workflow_dispatch:
    inputs:
      semverType:
        description: 'Semver Type'     
        required: true
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: General setup and install dependencies
        run: |
          git config --global user.name 'Release Bot'
          git config --global user.email 'simonbengtsson@users.noreply.github.com'
          npm install
  
  
      - name: Build and update version
        run: |
          echo "Type: ${{ github.event.inputs.semverType }}"
          npm version ${{ github.event.inputs.semverType }}
          
      - name: Deploy and publish
        run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        
