name: Playground

on:
  workflow_dispatch:
    inputs:
      semverVersion:
        description: 'Semver Version'     
        required: true
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      
      - name: Install dependencies
        run: npm install
          
      - name: Run tests
        run: npm run test
        
      - name: Generate build and types
        run: npm run build
        
      - name: Git
        run: |
          git config --global user.name 'Release Bot'
          git config --global user.email 'simonbengtsson@users.noreply.github.com'
          git add -A
          git commit -m "Build"
          git push
        
