# This is a basic workflow to help you get started with Actions

name: New Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      
      - name: Install dependencies
        run: npm install
          
      - name: Run tests
        run: npm run test
        
      - name: Generate build and types
        run: npm run build
        
      - name: Commit and push build files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build update

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
